Create Dockerfile, readme, License files, etc
femiwiki/cassandra pull request #1
Opened 2019-02-09 08:10 UTC by lens0021

- 기본 카산드라 이미지에 보안 관련 설정이 모두 열려 있던 것을 계정을 사용하도록 수정함

#### 관련 이슈

- https://github.com/femiwiki/femiwiki/issues/52

2019-02-13 06:25 UTC, simnalamburt requested changes
Reviewed

2019-02-13 06:25 UTC, simnalamburt commented on run
> +if [ -z "${DEV_PASSWORD:-}" ]; then ## TODO if 대신 짧게 줄이기
if 대신 짧게 줄이기가 혹시 `cond && foo || bar` 말씀하시는거라면 전 그냥 if-else 문 쓰는게 나은거같아요. 전 저거 알아보기 싫어서 안좋아해요.

2019-02-13 06:25 UTC, simnalamburt commented on run
> +  # Await until cassandra is started and normally errored
이 영어문장 의도하신 한글 뜻이뭐에요?

2019-02-13 06:25 UTC, simnalamburt commented on run
> +# Starting Cassandra and enabling password authentication script
`A script which starts Cassandra daemon and enables password authentication`로 고칩시다

2019-02-13 06:25 UTC, simnalamburt commented on run
> +  echo 'Creating keyspace has different name and the replication factor'
`Creating a new keyspace with a different name and a different replication factor`로 수정

2019-02-13 06:25 UTC, simnalamburt commented on run
> +# Create arbitarary passwords
arbitrary는 뉘앙스가 살짝 다른거같아요. 사용자 입력이 임의일때 주로 쓰는거같았어요. (ex: 임의의 입력이 들어와도 정상작동해야한다 -> it should function well with arbitrary inputs)

`Create random passwords with CSPRNG` 로 바꿉시다. CSPRNG는 https://en.m.wikipedia.org/wiki/Cryptographically_secure_pseudorandom_number_generator 의 약자

2019-02-13 06:25 UTC, simnalamburt commented on run
> +  echo "Generated ${USER_NAME:-femiwiki}'s password: ${USER_PASSWORD}"
`${USER_NAME:-femiwiki}` 반복해서 쓰면 디폴트값 차이나게 쓸 수 있으니

```
USER_NAME="${USER_NAME:-femiwiki}"
```

이런거를 위에서 쓰는게 나을거같아요

2019-02-13 06:25 UTC, simnalamburt commented on run
> +# Keep trying enabling authentication...
`Keep trying to activate password authentication until it succeeds` 로 수정

2019-02-13 06:56 UTC, lens0021 commented on run
> +  # Await until cassandra is started and normally errored
잘못 쓴 주석 같습니다. :cry:

"Await until cassandra is started ~~and normally errored~~"로 뒤에를 짜르겠습니다

2019-02-13 07:10 UTC, lens0021 commented on run
> +if [ -z "${DEV_PASSWORD:-}" ]; then ## TODO if 대신 짧게 줄이기
지웠습니당 :smile:

2019-02-13 07:11 UTC, lens0021 commented on run
> +# Starting Cassandra and enabling password authentication script
고쳤습니다 https://github.com/femiwiki/cassandra/commit/04b353e925a3bfadd9d56abaf4766419b5155cdf#diff-a53108f7543b75adbb34afc035d4cdf6R4

2019-02-13 07:12 UTC, lens0021 commented on run
> +  echo 'Creating keyspace has different name and the replication factor'
고쳤습니다 https://github.com/femiwiki/cassandra/commit/04b353e925a3bfadd9d56abaf4766419b5155cdf#diff-a53108f7543b75adbb34afc035d4cdf6R26

2019-02-13 07:19 UTC, lens0021 commented on run
> +  echo "Generated ${USER_NAME:-femiwiki}'s password: ${USER_PASSWORD}"
수정 했습니다 https://github.com/femiwiki/cassandra/commit/b83ba650a6195923cdcd14b4a805008a4c5e538d#diff-a53108f7543b75adbb34afc035d4cdf6

2019-02-13 07:19 UTC, lens0021 commented on run
> +# Keep trying enabling authentication...
수정 했습니다 https://github.com/femiwiki/cassandra/commit/04b353e925a3bfadd9d56abaf4766419b5155cdf#diff-a53108f7543b75adbb34afc035d4cdf6R47

2019-02-13 07:19 UTC, lens0021 commented on run
> +# Create arbitarary passwords
수정했습니다 https://github.com/femiwiki/cassandra/commit/b83ba650a6195923cdcd14b4a805008a4c5e538d#diff-a53108f7543b75adbb34afc035d4cdf6R15

2019-02-14 05:40 UTC, simnalamburt approved these changes
LGTM

2019-02-14 05:40 UTC, merged